import { strict as assert } from "node:assert";
import { execFileSync } from "node:child_process";
import { access, mkdtemp, mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { test } from "node:test";
import { adjudicateRun, adjudicationDryRun, buildJudgePacket, CodexJudgeAdapter, defaultJudgeConfig, defaultPacketLimits, JudgeAdapter, JudgeExecution, loadPhase2Run, validateJudgeResponse } from "../src/adjudication";
import { CandidateAdapter, CandidateExecution, CandidateRequest } from "../src/adapters";
import { runTrial } from "../src/runner";
import { Candidate, loadTrial, Trial } from "../src/trial";

const git = (cwd: string, args: string[]) => execFileSync("git", args, { cwd, encoding: "utf8" });
const clean = async (path: string) => rm(path, { recursive: true, force: true });
async function repository(parent: string): Promise<string> { const root = join(parent, "repository"); await mkdir(join(root, "src"), { recursive: true }); git(parent, ["init", root]); await writeFile(join(root, "package.json"), "{}\n"); await writeFile(join(root, "src", "base.ts"), "export const base = 1;\n"); git(root, ["config", "user.email", "arena@example.test"]); git(root, ["config", "user.name", "Arena"]); git(root, ["add", "."]); git(root, ["commit", "-m", "baseline"]); git(root, ["tag", "baseline"]); return root; }
function trial(repository: string, count = 2): Trial { const candidates: Candidate[] = Array.from({ length: count }, (_, index) => ({ id: `candidate-${index + 1}`, adapter: "codex-exec", harness: "codex-harness", provider: "provider-x", model: "model-x", attention: "variant-x", agent: "agent-x", profile: "profile-x" })); return { id: "phase3", repository, baselineRef: "baseline", taskContract: "Implement the requested inventory behavior and keep tests passing.", allowedPaths: ["src", "fixtures/bounded-inventory/src"], forbiddenPaths: ["secrets"], validationCommands: [[process.execPath, "-e", "process.stdout.write('ok')"]], timeoutMs: 1_000, validationTimeoutMs: 1_000, dependencyPolicy: "allow_changes", maxLaunchTransportRetries: 1, manualIntervention: "forbidden", provenance: {}, candidates }; }
class CleanAdapter implements CandidateAdapter { async doctor() { return { adapter: "fake", ok: true }; } async execute(request: CandidateRequest): Promise<CandidateExecution> { await writeFile(join(request.worktree, "src", "result.ts"), "export const result = true;\n"); await mkdir(join(request.worktree, "fixtures", "bounded-inventory", "src"), { recursive: true }); await writeFile(join(request.worktree, "fixtures", "bounded-inventory", "src", "inventory.ts"), "export function inventoryTotal(lines: Array<{ quantity: number; unitPrice: number }>): number { return Math.round(lines.reduce((sum, line) => sum + line.quantity * line.unitPrice, 0) * 100) / 100; }\n"); await writeFile(join(request.artifactDirectory, "stdout.log"), '{"type":"turn.completed"}\n'); await writeFile(join(request.artifactDirectory, "stderr.log"), ""); await writeFile(join(request.artifactDirectory, "final-response.txt"), "done\n"); return { args: ["fake"], startedAt: "2026-01-01T00:00:00.000Z", completedAt: "2026-01-01T00:00:00.010Z", durationMs: 10, exitCode: 0, timedOut: false }; } }
class ProvenanceAdapter extends CleanAdapter { async execute(request: CandidateRequest): Promise<CandidateExecution> { return { ...(await super.execute(request)), adapterProvenance: { executable: { source: "path", path: "codex", version: "codex-cli 0.144.0" } } }; } }
class EmptyAdapter extends CleanAdapter { async execute(request: CandidateRequest): Promise<CandidateExecution> { await writeFile(join(request.artifactDirectory, "stdout.log"), '{"type":"turn.completed"}\n'); await writeFile(join(request.artifactDirectory, "stderr.log"), ""); return { args: ["fake"], startedAt: "2026-01-01T00:00:00.000Z", completedAt: "2026-01-01T00:00:00.010Z", durationMs: 10, exitCode: 0, timedOut: false }; } }
function response(labels: string[], verdict: "RECOMMENDATION" | "TIE" | "INCONCLUSIVE" = "RECOMMENDATION") { const criteria = Object.fromEntries(labels.map((label) => [label, { acceptance_coverage: "strong", maintainability: "adequate", architecture_fit: "adequate", regression_risk: "adequate", unnecessary_complexity: "adequate", evidence_quality: "strong" }])); const tied = verdict === "TIE" ? labels.slice(0, 2) : verdict === "RECOMMENDATION" ? labels.slice(0, 1) : []; let next = 2; return { schema_version: "3.0", verdict, recommended_labels: tied, confidence: "low", ranking: labels.map((label, index) => ({ label, rank: tied.includes(label) ? 1 : verdict === "RECOMMENDATION" && index === 0 ? 1 : next++, tier: "adequate", rationale: "bounded evidence" })), criteria_by_candidate: criteria, strengths_by_candidate: Object.fromEntries(labels.map((label) => [label, []])), risks_by_candidate: Object.fromEntries(labels.map((label) => [label, []])), limitations: [], summary: "bounded" }; }
class FakeJudge implements JudgeAdapter {
  calls = 0; stagingDirectories: string[] = [];
  constructor(private readonly replies: string[], private readonly failure?: "timeout" | "launch" | "throw", private readonly inspect?: (directory: string) => Promise<void>) {}
  async doctor() { return { adapter: "fake", ok: true }; }
  async adjudicate(request: { prompt: string; staging_directory: string }): Promise<JudgeExecution> {
    const response_text = this.replies[this.calls++] ?? "{}"; this.stagingDirectories.push(request.staging_directory); await this.inspect?.(request.staging_directory);
    assert.doesNotMatch(request.prompt, /candidate-\d|codex-harness|model-x/);
    if (this.failure === "throw") throw new Error("simulated judge launch failure");
    if (this.failure) return { started_at: "2026-01-01T00:00:00.000Z", completed_at: "2026-01-01T00:00:00.010Z", wall_clock_ms: 10, exit_code: this.failure === "launch" ? null : 0, timeout: this.failure === "timeout", stdout: "", stderr: "", response_text, launch_error: this.failure === "launch" ? "launch failed" : null, failure_classification: this.failure, args: ["fake"] };
    return { started_at: "2026-01-01T00:00:00.000Z", completed_at: "2026-01-01T00:00:00.010Z", wall_clock_ms: 10, exit_code: 0, timeout: false, stdout: "", stderr: "", response_text, launch_error: null, failure_classification: null, args: ["fake"] };
  }
}
test("Codex judge permits isolated non-Git staging", { skip: process.platform !== "win32" }, async () => { const temporary = await mkdtemp(join(tmpdir(), "arena-judge-cli-")), command = join(temporary, "codex.cmd"), previous = process.env.ARENA_CODEX_EXECUTABLE; try { await writeFile(command, "@echo off\r\nexit /b 0\r\n"); process.env.ARENA_CODEX_EXECUTABLE = command; const execution = await new CodexJudgeAdapter().adjudicate({ staging_directory: join(temporary, "staging"), packet: {}, schema: {}, prompt: "test", config: defaultJudgeConfig }); assert.equal(execution.exit_code, 0); assert.ok(execution.args.includes("--skip-git-repo-check")); } finally { if (previous === undefined) delete process.env.ARENA_CODEX_EXECUTABLE; else process.env.ARENA_CODEX_EXECUTABLE = previous; await clean(temporary); } });
async function phase2Run(adapter: CandidateAdapter = new CleanAdapter(), count = 2, configured?: Trial) { const temporary = await mkdtemp(join(tmpdir(), "arena-phase3-")); const source = await repository(temporary), contract = configured ? { ...configured, repository: source, baselineRef: "baseline" } : trial(source, count); const result = await runTrial(contract, new Map([["codex-exec", adapter], ["opencode-run", adapter]]), join(temporary, "run")); return { temporary, directory: result.directory }; }
async function gateState(directory: string, count: number, excluded = -1): Promise<void> { for (let index = 1; index <= count; index++) { const path = join(directory, "candidates", `candidate-${index}`, "telemetry.json"), telemetry = JSON.parse(await readFile(path, "utf8")); telemetry.hard_gates = telemetry.hard_gates.map((gate: { id: string }) => ({ ...gate, status: index === excluded && gate.id === "required_validation_completed" ? "unavailable" : "passed", reason: index === excluded && gate.id === "required_validation_completed" ? "evidence unavailable" : "passed" })); telemetry.output.hard_gate_status.value = index === excluded ? "failed" : "passed"; await writeFile(path, JSON.stringify(telemetry)); } }
const labels = (packet: Record<string, any>) => packet.candidates.map((candidate: { label: string }) => candidate.label) as string[];
function assertStrictSchema(value: any): void { if (!value || typeof value !== "object" || Array.isArray(value)) return; if ("enum" in value || "const" in value) assert.equal(value.type, "string"); assert.equal("uniqueItems" in value, false); if (value.type === "object") { assert.equal(value.additionalProperties, false); assert.deepEqual([...(value.required ?? [])].sort(), Object.keys(value.properties ?? {}).sort()); } if (value.type === "array") assert.ok(value.items); Object.values(value).forEach(assertStrictSchema); }

test("Phase 2 task contract is canonical, portable, and hash-checked", async () => { const { temporary, directory } = await phase2Run(); try { const task = JSON.parse(await readFile(join(directory, "task-contract.json"), "utf8")), manifest = JSON.parse(await readFile(join(directory, "manifest.json"), "utf8")); assert.equal(task.objective, "Implement the requested inventory behavior and keep tests passing."); assert.deepEqual(task.instructions, []); assert.equal(task.task_contract_hash, manifest.task_contract_hash); assert.equal(manifest.task_contract_artifact, "task-contract.json"); task.task_contract_hash = "bad"; await writeFile(join(directory, "task-contract.json"), JSON.stringify(task)); await assert.rejects(() => loadPhase2Run(directory), /task contract integrity/); task.task_contract_hash = manifest.task_contract_hash; task.objective = "tampered objective"; await writeFile(join(directory, "task-contract.json"), JSON.stringify(task)); await assert.rejects(() => loadPhase2Run(directory), /task contract integrity/); } finally { await clean(temporary); } });

test("masking is stable across ordering and covers 2 through 27 candidates", () => { for (const count of [2, 6, 7, 26, 27]) { const candidates = Array.from({ length: count }, (_, index) => ({ id: `candidate-${index + 1}`, label: "", artifactDirectory: `candidates/candidate-${index + 1}`, telemetry: { output: { files_changed: { value: 0 }, lines_added: { value: 0 }, lines_deleted: { value: 0 }, validation_pass_count: { value: 0 }, validation_fail_count: { value: 0 } }, execution: { process_timeout: { value: false } }, change_analysis: { pre_validation: { changed_paths: [], untracked_paths: [] } }, evidence_completeness: { status: "complete" }, hard_gates: [] }, validation: { commands: [] }, provenance: { adapter_execution: {} }, diff: "" })); const base: any = { directory: "C:/safe".replace("C:/", "run/"), manifest: { run_id: "run", trial_id: "trial", task_contract_hash: "hash", normalized_trial_snapshot_hash: "snapshot" }, snapshot: {}, taskContract: { objective: "task", instructions: [], acceptance_criteria: [], allowed_paths: [], forbidden_paths: [], validation_commands: [] }, forbidden: candidates.map((candidate) => candidate.id), candidates }; const first = buildJudgePacket(base), second = buildJudgePacket({ ...base, candidates: [...candidates].reverse() }); assert.deepEqual(first.identityMap, second.identityMap); assert.equal(labels(first.packet).length, count); assert.equal(labels(first.packet).includes("AA"), count >= 27); } });

test("allowlisted packet sanitizes outputs, preserves relative diff files, rejects identities and enforces budgets", async () => { const { temporary, directory } = await phase2Run(); try { const run: any = await loadPhase2Run(directory); run.candidates[0].validation.commands[0].stdout = "C:\\private\\run\\out /home/user/out"; run.candidates[0].diff = "diff --git a/C:/private/worktree/src/result.ts b/C:/private/worktree/src/result.ts\n--- C:/private/worktree/src/result.ts\n+++ C:/private/worktree/src/result.ts\n@@ -1 +1 @@\n-old\n+new"; const packet = buildJudgePacket(run, { ...defaultPacketLimits, diff_chars: 80 }); const rendered = JSON.stringify(packet.packet); assert.match(rendered, /a\/src\/result.ts/); assert.match(rendered, /<path:redacted>/); assert.doesNotMatch(rendered, /candidate-1|codex-harness|provider-x|model-x|variant-x|agent-x|profile-x|C:\\private|\/home\/user/); assert.ok(rendered.length <= Number((packet.packet.limits as any).packet_chars)); for (const forbidden of [...run.forbidden.substring, String(run.candidates[0].telemetry.provenance.configuration_hash)]) { run.candidates[0].diff = `+${forbidden}`; assert.throws(() => buildJudgePacket(run), /identity or path policy/); } for (const forbidden of run.forbidden.token) { run.candidates[0].diff = `+attention: ${forbidden}`; assert.throws(() => buildJudgePacket(run), /identity or path policy/); } run.candidates[0].diff = "+safe"; assert.throws(() => buildJudgePacket(run, { ...defaultPacketLimits, packet_chars: 32 }), /budget/); } finally { await clean(temporary); } });

test("token identity matching protects leaks without rejecting normal words", async () => { const proof = await loadTrial(join(process.cwd(), "examples", "bounded-fix", "phase3-proof.yml")); const { temporary, directory } = await phase2Run(new ProvenanceAdapter(), 2, proof); try { const run: any = await loadPhase2Run(directory), responseWithPath: any = response(["A"]); assert.ok(run.forbidden.token.includes("low")); assert.ok(run.forbidden.substring.includes("codex")); assert.equal(run.forbidden.substring.includes("path"), false); assert.equal(run.forbidden.substring.includes("codex-cli 0.144.0"), false); run.candidates[0].validation.commands[0].stdout = "npm run build"; assert.doesNotThrow(() => buildJudgePacket(run)); run.candidates[0].telemetry.hard_gates[0].reason = "allowed paths policy passed"; assert.doesNotThrow(() => buildJudgePacket(run)); run.forbidden.token.push("medium", "high"); for (const value of ["low", "medium", "high", "build"]) for (const leak of [`reasoning effort: ${value}`, `\"attention\": \"${value}\"`]) { run.candidates[0].diff = `+${leak}`; assert.throws(() => buildJudgePacket(run), /identity or path policy/); } run.candidates[0].diff = "+allowed flow lower following paths"; assert.doesNotThrow(() => buildJudgePacket(run)); responseWithPath.summary = "allowed paths"; assert.doesNotThrow(() => validateJudgeResponse(responseWithPath, ["A"], new Set(["A"]), { substring: [], token: ["path"] })); responseWithPath.summary = "agent: path"; assert.throws(() => validateJudgeResponse(responseWithPath, ["A"], new Set(["A"]), { substring: [], token: ["path"] }), /policy/); for (const value of [run.candidates[0].id, String(run.candidates[0].telemetry.provenance.model), String(run.candidates[0].telemetry.provenance.configuration_hash), "codex-exec", "C:\\private\\worktree"]) { run.candidates[0].diff = `+${value}`; assert.throws(() => buildJudgePacket(run), /identity or path policy/); } run.candidates[0].diff = "+safe"; const dry: any = await adjudicationDryRun(directory); assert.equal(dry.packet_valid, true); assert.equal(dry.labels.length, 2); } finally { await clean(temporary); } });

test("strict response validation handles recommendation, tie, inconclusive, and invalid label/rank cases", () => { const names = ["A", "B", "C"], eligible = new Set(names); for (const verdict of ["RECOMMENDATION", "TIE", "INCONCLUSIVE"] as const) assert.equal(validateJudgeResponse(response(names, verdict), names, eligible).verdict, verdict); const unknown = response(names); unknown.ranking[0].label = "Z"; assert.throws(() => validateJudgeResponse(unknown, names, eligible), /invalid/); const omitted = response(names); omitted.ranking.pop(); assert.throws(() => validateJudgeResponse(omitted, names, eligible), /invalid/); const duplicate = response(names); duplicate.ranking[1].rank = 1; assert.throws(() => validateJudgeResponse(duplicate, names, eligible), /invalid/); const duplicateRecommendation = response(names); duplicateRecommendation.recommended_labels = ["A", "A"]; assert.throws(() => validateJudgeResponse(duplicateRecommendation, names, eligible), /invalid/); const excluded = response(names); assert.throws(() => validateJudgeResponse(excluded, names, new Set(["A", "B"])), /invalid/); const leaked = response(names); leaked.summary = "C:\\private\\candidate-1"; assert.throws(() => validateJudgeResponse(leaked, names, eligible, ["candidate-1"]), /policy/); });

test("controller maps recommendation and exclusions, preserves one safe repair, and distinguishes outcomes", async () => { const { temporary, directory } = await phase2Run(undefined, 3); try { await gateState(directory, 3, 3); const run = await loadPhase2Run(directory), built = buildJudgePacket(run), packet = built.packet, all = labels(packet), excluded = Object.entries(built.identityMap).find(([, id]) => id === "candidate-3")![0], eligible = all.filter((label) => label !== excluded), repaired: any = response(all); repaired.ranking = response(eligible).ranking; const judge = new FakeJudge(["{malformed", JSON.stringify(repaired)]); const evaluation: any = await adjudicateRun(directory, judge); assert.equal(judge.calls, 2); assert.equal(evaluation.outcome, "RECOMMENDATION"); assert.ok(evaluation.recommended_candidate_id); assert.equal(evaluation.candidates.at(-1).eligibility, "excluded"); assert.deepEqual(evaluation.candidates.at(-1).exclusion_gates[0], { id: "required_validation_completed", status: "unavailable", reason: "evidence unavailable" }); const repair = JSON.parse(await readFile(join(directory, "judge-repair-request.json"), "utf8")); assert.match(repair.malformed_original_response, /malformed/); assert.match(repair.prompt, /Repair structure only/); } finally { await clean(temporary); } });

test("no winner, invalid repair, timeout, and launch never invoke more than one repair", async () => { const noWinner = await phase2Run(new EmptyAdapter()); try { const judge = new FakeJudge([]); assert.equal((await adjudicateRun(noWinner.directory, judge)).outcome, "NO_WINNER"); assert.equal(judge.calls, 0); } finally { await clean(noWinner.temporary); } const invalid = await phase2Run(); try { await gateState(invalid.directory, 2); const judge = new FakeJudge(["bad", "still bad", "third"]); assert.equal((await adjudicateRun(invalid.directory, judge)).outcome, "INCONCLUSIVE"); assert.equal(judge.calls, 2); } finally { await clean(invalid.temporary); } for (const failure of ["timeout", "launch"] as const) { const item = await phase2Run(); try { await gateState(item.directory, 2); const judge = new FakeJudge([], failure); assert.equal((await adjudicateRun(item.directory, judge)).outcome, "INCONCLUSIVE"); assert.equal(judge.calls, 1); } finally { await clean(item.temporary); } } });

test("judge staging is isolated, contains only masked inputs, and is removed after every outcome", async () => { const success = await phase2Run(); try { await gateState(success.directory, 2); const judge = new FakeJudge([JSON.stringify(response(labels(buildJudgePacket(await loadPhase2Run(success.directory)).packet)))], undefined, async (staging) => { assert.equal(resolve(staging).startsWith(resolve(success.directory)), false); assert.deepEqual((await readdir(staging)).sort(), ["judge-output-schema.json", "masked-judge-input.json"]); await assert.rejects(() => access(join(staging, "candidates", "candidate-1", "telemetry.json"))); }); await adjudicateRun(success.directory, judge); const staging = judge.stagingDirectories[0]; await assert.rejects(() => access(staging)); const artifactNames = (await readdir(success.directory)).filter((name) => /\.(json|txt)$/.test(name)); const serialized = await Promise.all(artifactNames.map((name) => readFile(join(success.directory, name), "utf8"))); assert.doesNotMatch(serialized.join("\n"), new RegExp(staging.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i")); assert.equal((await readdir(success.directory)).includes(".judge-staging"), false); } finally { await clean(success.temporary); }
  for (const failureKind of ["throw", "timeout"] as const) { const failure = await phase2Run(); try { await gateState(failure.directory, 2); const judge = new FakeJudge([], failureKind); assert.equal((await adjudicateRun(failure.directory, judge) as any).outcome, "INCONCLUSIVE"); await assert.rejects(() => access(judge.stagingDirectories[0])); } finally { await clean(failure.temporary); } } });

test("dry run writes only an inspectable preview and does not block real adjudication", async () => { const { temporary, directory } = await phase2Run(); try { const dry: any = await adjudicationDryRun(directory); const preview = join(directory, dry.preview_directory); assert.equal(dry.preview_directory, "phase3-preview"); assert.equal(dry.reasoning_effort, "low"); assert.ok(dry.packet_size <= dry.packet_limit); assert.match(JSON.stringify(dry.command_shape), /read-only.*ephemeral/); assert.ok(dry.command_shape.includes("--skip-git-repo-check")); assert.deepEqual((await readdir(preview)).sort(), ["dry-run.json", "judge-output-schema.json", "masked-judge-input.json"]); assertStrictSchema(JSON.parse(await readFile(join(preview, "judge-output-schema.json"), "utf8"))); for (const name of ["identity-map.json", "evaluation.json", "adjudication.json"]) await assert.rejects(() => access(join(directory, name))); await adjudicationDryRun(directory); assert.deepEqual((await readdir(preview)).sort(), ["dry-run.json", "judge-output-schema.json", "masked-judge-input.json"]); await gateState(directory, 2); const judge = new FakeJudge([JSON.stringify(response(labels(buildJudgePacket(await loadPhase2Run(directory)).packet)))]); assert.equal((await adjudicateRun(directory, judge) as any).outcome, "RECOMMENDATION"); assert.equal(judge.calls, 1); } finally { await clean(temporary); } });
